import type { Metadata } from "next";
import '@styles/app/app.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
		<html lang="en">
			<head>
				<meta charSet="utf-8" />
				<title>My Cool Resume</title>
			</head>
			<body className={`antialiased grid min-h-screen place-items-center bg-gray-400 print:min-h-0`}>
				<main
					className="m-4 h-[297mm] w-[210mm] overflow-hidden rounded-md bg-white p-8 shadow-lg print:m-0 print:h-screen print:w-screen print:rounded-none print:shadow-none"
				>
					{children}
				</main>
			</body>
		</html>
  );
}

export default RootLayout
