import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
		<html lang="en">
			<head>
				<meta charSet="utf-8" />
				<title>My Cool Resume</title>
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased grid min-h-screen place-items-center bg-gray-400 print:min-h-0`}>
				<main
					className="m-4 h-[297mm] w-[210mm] overflow-hidden rounded-md bg-white p-8 shadow-lg print:m-0 print:h-screen print:w-screen print:rounded-none print:shadow-none"
				>
					{children}
				</main>
			</body>
		</html>
  );
}

export default RootLayout
